# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_download_insecure = true
  
  config.vm.network "private_network", ip: "192.168.56.201"
  config.vm.network "public_network"
  config.vm.hostname = "postgres1"
  
  config.vm.provider "virtualbox" do |vb|
      vb.name = "postgres1"
      vb.memory = 2048
	  vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y postgresql-13 postgresql-13-repmgr barman-cli
  SHELL
end
